[http]
    [http.middlewares]

        [http.middlewares.api-stripprefix.stripPrefix]
            prefixs = ["/api/v1"]
    
    [http.routes]

        [http.routes.app-http]
            entryPoints = ["http"]
            service = "app"
            rule = "PathPrefix(`/api/v1`)"
            middlewares = ["api-stripprefix"]
    
    [http.services]

        [http.services.app]
            [http.services.app.loadBalancer]
                [[http.services.app.loadBalancer.servers]]
                    url = "http://127.0.0.1:8000"